default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config
        args:
        - --exclude=tests/.*\.py
        - --application-directories=".:oesas:tasks:standalone:init/app/main"
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
    -   id: autopep8
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --ignore=E114,E115,E116,E133,E401,E501,E701,W292
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-added-large-files
      args:
      - --maxkb=512
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
#    - id: no-commit-to-branch
#      args: [--pattern, ^\d+\.\d+\.\d+-dev$, --pattern, ^\d+\.\d+\.\d+-vpc$]
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        exclude: third
        args:
        - --ignore=W503,W504,E123,E127,E203,E225,E241,E261,E265,E303,E501,F403,F405,C901
